export const TEXT = {
  title:'СВОД ГОДОВЫХ СВЕДЕНИЙ  ОБ ОБЩЕДОСТУПНЫХ (ПУБЛИЧНЫХ) БИБЛИОТЕКАХ СИСТЕМЫ МИНКУЛЬТУРЫ РОССИИ',
  enterTerritory: 'Введите регион',
  search: 'Поиск',
  list: 'Список регионов',
  sorting: 'Сортировка',
  byDefault: 'по умолчанию',
  byAlphabeticalOrder: 'по списку регионов',
  byLibraryNumber: 'по числу библиотек',

  fullName:'Полное наименование',
  address: 'Адрес',
  employeesTotal: 'Всего сотрудников',
  employeesStaff: 'Сотрудников в штате',
  libraries: 'Библиотек',
  librariesWithComputers: 'Библиотек, оснащенных компьютерами',
  users: 'Пользователей',
  childrenUsers: 'Пользователей детского возраста',
  subscribers: 'Интернет подписчиков',
  visiters: 'Посетителей',
  internetVisiters: 'Интернет посетителей',
};
